export const ADD_JOURNAL_ENTRY = 'ADD_JOURNAL_ENTRY';
export const REID_JOURNAL_ENTRY = 'REID_JOURNAL_ENTRY';
export const DELETE_JOURNAL_ENTRY = 'DELETE_JOURNAL_ENTRY';
export const AUTHORISE = 'AUTHORISE';
export const DEAUTHORISE = 'DEAUTHORISE';

export const GET_JOURNAL_ENTRIES = 'GET_JOURNAL_ENTRIES';
